
'''for arrays'''

commands = ["show user info,show user pass, cal, time , shut down,launch clock, study,pc info, mine, snake, #say  "]
game = ["mine, snake, Bubble Blaster, launch clock"]
entry = ""
users = ["admin"]
password = ["admin12"]
computer_on = 2
computer_off = 1
input_name = ""
input_pass = ""
input_name_2 = ""
time_input = ""
file_name = ["history", "sci", "geo", ]
file_name_define_history = ["ch one", "ch two"]
file_ch_input = ""
file_name_define_histotry = ""
file_info_hist_for_ch_one = "french revolution"
input_file_name = ""
ch_note_history = (
    "The French Revolution was a period of time in France when the people overthrew the monarchy and took control of the government.")
ch_note_history_2 = ("The French Revolution lasted 10 years from 1789 to 1799.")
ch_note_history_3 = ("It began on July 14, 1789 when revolutionaries stormed a prison called the Bastille")
note_ch_one_history = ""
students_name = ["abdus", "rony", "mike"]
students_atendenc_type = ["A", "P"]
students_name_input = ""
students_atendenc_input = ""
student_no = (3)
student_enter = ""
students_atendenc_type_A = ""
students_atendenc_type_P = ""
say_input = ""
GUI_IN_ = ""
a = "!"
b = "@"
c = "#"
d = "$"
e = "%"
f = "^"
g = "&"
h = "*"
i = "!!"
j = "@@"
K = "##"
l = "$$"
m = "%%"
n = "^^"
o = "&&"
p = "!!!"
q = "@@@"
r = "$$$"
s = "%%%"
t = "^^^"
u = "&&&"
v = "***"
w = "!!!!"
x = "@@@@"
y = "####"
z = "$$$$"
force_S_in = ""
say_input_root = ""
root_pass = "root12"
root_shut = ""
comm = ""
host_name = "localhost"
user_name = "root"
password_of_user = "password"
database_name = "anex"
passs = "admin"
outPut = ""
all_commands = ["show all info", "show info", "show pass", "show databases", "show private info of", "end"]